version: '3'

networks:
  internal-network:
    internal: true
    driver: bridge
  external-network:
    driver: bridge

services:
  proxy:
    build: .
    networks:
      - internal-network
      - external-network

  app:
    build: example-app/.
    networks:
      - internal-network
