name: ci

on: push

env:
  DOCKER_REPOSITORY_NAME: remote-host-proxy

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set DOCKER_TAG
        run: >-
          if [ ${GITHUB_REF#refs/heads/} = 'main' ]; then
            echo "DOCKER_TAG=latest" >> $GITHUB_ENV;
          elif [ ${GITHUB_REF#refs/heads/} = 'staging' ]; then
            echo "DOCKER_TAG=staging" >> $GITHUB_ENV;
          else
            echo "DOCKER_TAG=$GITHUB_SHA" >> $GITHUB_ENV;
          fi

      - name: Build, tag, and push image to Dockerhub
        run: |
          docker build -t biolib/$DOCKER_REPOSITORY_NAME:$DOCKER_TAG .
          echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin &&
          docker push biolib/$DOCKER_REPOSITORY_NAME:$DOCKER_TAG
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_PASS: ${{ secrets.DOCKERHUB_PASS }}
